.libPaths(new = "rlibs", include.site = TRUE)
cat("where we")
print(list.files())
#print(list.files(~))
.libPaths(new = "/usr/local/lib/R/4.3/site-library", include = T)
library(rmarkdown,lib.loc="rlibs")#,lib.loc = "/usr/local/lib/R/4.3/site-library")
library(yaml,lib.loc="rlibs")
library(jquerylib,lib.loc="rlibs")
#library(knitr,lib.loc = "/usr/local/lib/R/4.3/site-library")
#?render_markdown()
#?knit
#?output_format
#knit("pages/README.Rmd",output="pages/index.html")
#render("wp001.Rmd",output_file ="wp001.html",run_pandoc=T)
print("from renderscript")