system("python3 --version",intern = T)
system("which python3")
system("pip3 list")
system("ls",intern = T)
library(reticulate)
system("which python")
py_config()
library(reticulate)
#use_virtualenv("r-miniconda")
# use_python_version()
#py_eval("1+1")
#py_list_packages()
#py_install("transliterate")
# py_discover_config()
#py_config()
#use_miniconda("/Users/guhl/Library/r-miniconda/bin/python") # on lapsi!
#system(paste0("quid compare ",txt.src," ",txt.target),intern = T)
