print(2/100)
print("testrun")
#install.packages("knitr")
#Sys.setenv(R_CRAN_WEB = "https://cloud.r-project.org")
install.packages("knitr",contriburl = "https://cloud.r-project.org/src/contrib")
#install.packages("rmarkdown",contriburl = "https://cloud.r-project.org/bin/macosx/contrib/4.1")
print(getOption("repos"))