print(2/100)
print("testrun")
#install.packages("knitr")
Sys.setenv(R_CRAN_WEB = "https://cloud.r-project.org")
install.packages("knitr",repos=getOption("repos"),contriburl = "https://cloud.r-project.org")
install.packages("rmarkdown")#,contriburl = "https://cran.uni-muenster.de")
print(getOption("repos"))