name: inst R cached
on:
  push:
    branches: [ pages ]
  pull_request:
    branches: [ main ]
#name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: r-lib/actions/setup-r@master
      #   with:
      #       r-version: '3.6.1'
      - name: Install libcurl
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Query dependencies
        run: Rscript -e "install.packages('remotes', repos = "https://cloud.r-project.org")" -e "saveRDS(remotes::dev_package_deps(dependencies = TRUE), 'depends.Rds')"
      - name: Cache R packages
#        if: runner.os != 'Windows'
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-3.6.1-${{ hashFiles('depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-3.6.1-
      - name: Install renv 0.9.2
        run: Rscript -e "install.packages('https://cran.r-project.org/src/contrib/renv_0.9.2.tar.gz', repos = NULL, type = 'source')"
      - name: Install rcmdcheck 1.3.3
        run: Rscript -e "install.packages('https://cran.r-project.org/src/contrib/rcmdcheck_1.3.3.tar.gz', repos = NULL, type = 'source')"
      - name: Check
        run: Rscript -e "renv::restore();rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'error')"