name: R workflow
on:
  push:
    branches: [ pages ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
    - name: Install dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
         packages: |
          tidyverse
          remotes
          stringi
          readr
          httr
          jsonlite
          rmarkdown
          markdown
          devtools
          knitr
          quanteda
          readtext
          readxl
          xml2
          purrr
          tinytex
          RecordLinkage
          R.utils
          writexl
          udpipe
          syuzhet
          rlang
          png
          graphics
          lme4
          stats
          htmltools
          googlesheets4
          ggplot2
          bookdown
          abind
           
    - name: R CMD check
      run: |
        installed.packages()
      shell: Rscript {0}
    
    #########################

    - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: build book
        #run: mdbook build -d ./mdbook/workflow/book
        run: |
           source("scripts/testrun.R")
           source("pages/knitpagesrmd.R")
        shell: Rscript {0} 
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./pages
      # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2