name: R workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
   # - name: Set up R
    #  uses: r-lib/actions/setup-r@v1
    - name: Install dependencies
      uses: r-lib/actions/setup-r-dependencies@v1
      with:
        packages: |
#          tidyverse
          jsonlite
 #         remotes
    - name: R CMD check
      run: |
       #  R CMD build .
       # R CMD check *tar.gz
       installed.packages()
      shell: Rscript {0}
